### PR TITLE
fix annoying bug with subplots in rows

### PR DESCRIPTION
**Pull request by ghtmtt**
@nyalldawson a super small code fix discovered during Italian [QGIS SummerCamp](http://qgis.it/summer_camp.html)

### CODE REVIEW

**Comment by ghtmtt** [comment]
@nyalldawson don't know why Travis is failing, if this could be related to the refactoring or to something else. I tried it with the last version (before refactoring) and it works nice. We can drop it and open an issue for a future fix

**Comment by nyalldawson** [comment]
It's the pylint error raised by this change:

"-----------------
Pylint violations
-----------------
************* Module DataPlotly.data_plotly_plot
DataPlotly/data_plotly_plot.py:763:55: W0613: Unused argument 'tit_lst' (unused-argument)"

**Comment by ghtmtt** [comment]
so due to some syntax error and not to the code changes?

**Comment by nyalldawson** [comment]
No, it is the code change. Travis is running pylint as part of the checks, which is detecting that since you've dropped the titlist variable use in this line that variable is no longer used anywhere. Can you completely remove that variable?

(You can run "make pylint" locally to run this check on your computer)

**Comment by ghtmtt** [comment]
> No, it is the code change. Travis is running pylint as part of the checks, which is detecting that since you've dropped the titlist variable use in this line that variable is no longer used anywhere. Can you completely remove that variable?

done! Travis is green ;)

**Pull request merged**
