### PR TITLE
ENH: add french translation

### PR DESCRIPTION
**Pull request by SebastienPeillet**
Hi,

I translated your plugin to french ! Thank for your work!

Sébastien Peillet

### CODE REVIEW

**Comment by ghtmtt** [comment]
Thanks @SebastienPeillet we will merge this ASAP!

**Comment by ghtmtt** [comment]
@SebastienPeillet I downloaded your ts file and uploaded in Transifex, the official tool we use to translate strings. Here the link: https://www.transifex.com/dataplotly/

If you subscribe and ask to join the team of DataPlotly I'll be very happy to accept you. There are only 15 more strings to have a complete French translation!

**Comment by SebastienPeillet** [comment]
Hi !

Sorry, I took a long time to answer. I created a profile on transifex and I would be glad to finish the translation !

**Comment by ghtmtt** [comment]
@SebastienPeillet I accepted you in Transifex team. Strings are there and once the fully UI is finished I will pull the strings and merge them into the repository. I'm closing this PR since it is outdated. Thanks for your contribution!

**Pull request closed without merging**
