### PR TITLE
Expose Dataplotly on QGIS Server for a GetPrint request

### PR DESCRIPTION
**Pull request by Gustry**
If Dataplotly is installed on QGIS Server, it's possible to create PDF having a DataPlotly layout item

http://qgis.server/master?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&MAP=/home/etienne/tmp/dataplotly.qgs&TEMPLATE=Layout%201&CRS=EPSG:4326&FORMAT=png&map0:EXTENT=47.272404,6.104795,47.415845,6.589646&

Screenshot from 2021-09-25 13-00-36

### CODE REVIEW

**Comment by ghtmtt** [comment]
@Gustry that's really awesome!! The link is not working, can you post a working one? What do you think @nyalldawson? Are we going to another super DataPlotly feature? :)

**Comment by Gustry** [comment]
> The link is not working, can you post a working one?

Yes, this was just a example of my URL on my computer.
I don't have yet DataPlotly on a public server so I can't share a link. It was just a preview to give the GetPrint request example and to see the result in my Firefox ;-)

**Comment by ghtmtt** [comment]
I don't see any reason not to merge this.

**Comment by ghtmtt** [comment]
> I don't have yet DataPlotly on a public server so I can't share a link. It was just a preview to give the GetPrint request example and to see the result in my Firefox ;-)

if/when you get a public server available with a working example, just share a link so we can add it to the readme and documentation!

**Comment by Gustry** [comment]
Thanks for the merge.

When are you planning to make a new release ?
Maybe I can still add a few commits ? Do you mind if I add QGIS-plugin-ci for the packaging of the plugin ? https://github.com/opengisch/qgis-plugin-ci

> if/when you get a public server available with a working example, just share a link so we can add it to the readme and documentation!

I will for sure ! Stay tuned

**Comment by ghtmtt** [comment]
> When are you planning to make a new release ?

already done :) but nevermind, I'll make new point releases if you are adding some other stuff

> Maybe I can still add a few commits ? Do you mind if I add QGIS-plugin-ci for the packaging of the plugin ? https://github.com/opengisch/qgis-plugin-ci

I've never used that tool, but could be useful, so I'm OK with that, thanks!

**Pull request merged**
