### PR TITLE
Add options to change title, xticks and yticks font sizes.

### PR DESCRIPTION
**Pull request by giliam**
Insert options in graph parameters to change settings for all three parameters.

Could be refined to also change x_label and y_label font sizes (if such parameters exist)

See #208

### CODE REVIEW

**Comment by ghtmtt** [comment]
@giliam I'm testing the PR but it seems that the `Title font size` is changing not only the title size but also all the labels and legend sizes:

image

We can be more specific, using per item parameters:

```
fig.layout.title.font.size = 100
fig.layout.xaxis.titlefont.size = 50
fig.layout.yaxis.titlefont.size = 50
```
ref: https://plotly.com/python/figure-labels/

all the new entries are set by default to 1 in the UI and it makes all the labels and ticks too small to be seen:

image

Thanks for the great work!

**Comment by giliam** [comment]
> @giliam I'm testing the PR but it seems that the `Title font size` is changing not only the title size but also all the labels and legend sizes:
> 
> image
> 
> We can be more specific, using per item parameters:
> 
> ```
> fig.layout.title.font.size = 100
> fig.layout.xaxis.titlefont.size = 50
> fig.layout.yaxis.titlefont.size = 50
> ```
> 
> ref: https://plotly.com/python/figure-labels/
> 
> all the new entries are set by default to 1 in the UI and it makes all the labels and ticks too small to be seen:
> 
> image
> 
> Thanks for the great work!

I will have a look, thank you very much for your inputs!

**Comment by ghtmtt** [comment]
@giliam since the situation is a little bit crowded, can I also suggest to use a `QgsCollapsibleGroup` in the UI? So we can have all the label font settings within a group with a cleaner interface?

**Comment by giliam** [comment]
What do you say about this? I hope I'm not breaking anything in the ui Qt part as diff logs are quite big and not that much logical. Thanks again for your help and for that great plugin!

**Comment by ghtmtt** [comment]
looks good to me! Some thoughts.

* can we start the group as collapsed?
* the default font sizes in the main plot UI are still = 1, can you change it to another more visible size?

**Comment by ghtmtt** [comment]
@giliam do you need some help? I'm really keen to review your contribution and to release an updated version of the plugin!

**Comment by giliam** [comment]
Sorry @ghtmtt, I had no time in the last few days. I just pushed an update with your suggestions. Tell me if anything else needs to be changed! :)

**Comment by ghtmtt** [comment]
@giliam fantastic PR! I tested it and it works perfectly! Can I just ask to put the default font size to 10 in both UI and code? 20 is a little bit too big IMHO.

After that I will merge it and make the new release!

**Comment by giliam** [comment]
Done @ghtmtt! 
Just have a small blunder, it seems like the tab order is kind of messed up. We should try to clean this, no? 
I just discovered this (https://doc.qt.io/archives/qt-4.8/designer-tab-order.html#:~:text=easier%20to%20use.-,Setting%20the%20Tab%20Order,position%20in%20the%20tab%20order.).

**Comment by giliam** [comment]
Great idea although I have no idea how this `QgsFontButton` works. I might have some time to look into it in the next week...

**Comment by ghtmtt** [comment]
@giliam, wow, super work! And you said you didn't have any clue of what a `QgsFontButton` was :)

For you question, I think, but @nyalldawson for sure could be more helpful, that the function `write_to_project` https://github.com/ghtmtt/DataPlotly/blob/master/DataPlotly/core/plot_settings.py#L215 is the one responsible of the conversion of suitable XML tags of proper QGIS elements.

**Comment by nyalldawson** [comment]
Actually in this scenario QgsTextFormat isn't an option -- that's the full blown class with all the shadow/buffer/etc options. But here we need a cut down set of options, as we have to match what is possible in plotly. 

You can still use the QgsFontButton though -- you just need to set the mode for the button to QFont mode (see https://qgis.org/pyqgis/master/gui/QgsFontButton.html#qgis.gui.QgsFontButton.setMode ). That'll give a restricted set of properties with just font Family/style/size.

**Comment by giliam** [comment]
Thank you all for your answers. My problem with `QFont` is that it seemed to me that @ghtmtt wanted to add some color. As far as I understand it, `QFont` doesn't include color. That's why I used `QgsTextFormat` in current system.

**Comment by ghtmtt** [comment]
@giliam yep I'd like to enhance the size with also some other useful stuff like color, size and font. As @nyalldawson suggested, we don't need to use `QFont` rather we can still use `QgsFontButton` but in a *simplified* way by setting the Mode to 1 (`QgsFontButton.ModeQFont`).

I'd say that we don't have color available, but we can use another button with the color. Basically we have to set all the properties *by hand* (size, font, eventually the color) and grab them as values from the widgets we are using rather the using the `QgsTextFormat` class.

Does it make sense?

**Comment by giliam** [comment]
I guess something like that?

image

**Comment by ghtmtt** [comment]
@giliam exactly what I was thinking!

**Comment by giliam** [comment]
I'm sorry but I still don't really get how to store `QFont `in settings. I guess I should go through `plot_settings.py` and add properties for my elements. But should I divide into _Size_, _Family_ and _Color_ or is there a way I can store the whole `QFont` item?

**Comment by ghtmtt** [comment]
trying the PR and it is working great! I have a test failure but not related to this PR. I tested it also with an project with the `master` version of the plugin (so without the new items) and back-forth seems working nice without breaking anything.

Did you run some tests on your computer?

**Comment by giliam** [comment]
Great, nice to read that!

Unit tests you mean? No :'(
I tried following tests:
* Open existing projet with graph and check the settings where stored and they did
* Open new project, create plot live and in layouts, and it worked too.

Do you think of anything else?

**Comment by ghtmtt** [comment]
> Unit tests you mean? No :'(

yep. you should set up the environment first by cd in the plugin folder and then run `source scripts/run-env-linux.sh` (if you are on a linux machine) and then just run `make test`

> Do you think of anything else?

we just have to be sure that old projects vs new projects (and vice versa) are not broken. It seems they are working fine though :)

**Comment by giliam** [comment]
I'm sadly under Windows but I have a WSL 2 running and I was able to perform the tests. The only one failing is `test_qgis_environment` in `QGISTest`. Should I write some additional tests?

**Comment by ghtmtt** [comment]
it would be super great if you can add some tests yes!

**Comment by ghtmtt** [comment]
sorry for the late reply. The best tip I can give you is to have a look at existing tests and before to commit them, run them locally (as you already did).

The folder to have a look at is of course this: https://github.com/ghtmtt/DataPlotly/tree/master/DataPlotly/test. Within it you have some layers available that you can use to run the tests.

The `test_data_plotly_dialog.py` (https://github.com/ghtmtt/DataPlotly/blob/master/DataPlotly/test/test_data_plotly_dialog.py) is for the main dialog interface: testing the dialog window, reading and writing the project, and so one.

The `test_plot_factory.py` (https://github.com/ghtmtt/DataPlotly/blob/master/DataPlotly/test/test_plot_factory.py) is the file that run tests of the plot_factory, while the important file for this PR is https://github.com/ghtmtt/DataPlotly/blob/master/DataPlotly/test/test_plot_settings.py because it tests what is going on with the settings of each single plot *item*.

You can have a look for example at these PRs (https://github.com/ghtmtt/DataPlotly/pull/194/files, https://github.com/ghtmtt/DataPlotly/pull/180/files) to have an idea when something is added where should it tested.

**Comment by giliam** [comment]
Hi @ghtmtt , sorry again I had quite a lot to do recently. Here is a first few tests. I have two questions maybe: 
* should I run exhaustive tests on all parameters (I just tested a few of them)
* should I also add a test to `test_plot_factory` to test the real effect of the settings?

**Comment by giliam** [comment]
Like that?

**Comment by ghtmtt** [comment]
yes! I'm merging the PR and make a new release soon! Many thanks for all the work, and I hope we can collaborate also in the future!

**Comment by giliam** [comment]
Thank you for your help and for this nice project! Agreed for future collaboration :)

**Comment by ghtmtt** [comment]
@giliam I've released the 3.9 version of the plugin! Many many thanks for your awesome work!

**Comment by soester** [comment]
@ghtmtt i have installed the dev version of the plugin you gave out in the workshop on the QGIS Usergroup meeting in Bern.
Should it allready be possible to also change legend font style? Or should i open a new issue about that?

By the way: the Worksop was great!

**Comment by ghtmtt** [comment]
@soester yes please! This PR has changed *only* the behavior of the axes and the titles, and not the ticks

**Comment by pedrogeo** [comment]
Hi,

I use DataPlotly plugin (v. 3.9.2) in QGIS 3.28.2. It's a very useful plugin and a nice work from the devs.

I have a problem with the size of the fonts (title, labels and ticks). When I modify the size or the font type, there is no change in the graphic. Is it a bug or am I doing it the wrong way ?

text

graph

Pierre

**Comment by ghtmtt** [comment]
are you referring to the *standard* plugin or the plugin used in the print layout? In both cases the font size could not correspond to what you expect because the plot is created within a html frame, therefore you might have to use bigger font sizes

**Comment by pedrogeo** [comment]
I uses both in the plugin in the print layout (in a report precisely) and in the standard plugin and the results are the same. Even I put a font size at 72, the label font does not change. The font style does not change too if I put Italic or Bold style.

**Comment by pedrogeo** [comment]
It seems that the problem appears with the "pie chart" graphic type. I manage to modify the font size with the "bar plot" graphic type.

**Comment by apullar** [comment]
> It seems that the problem appears with the "pie chart" graphic type. I manage to modify the font size with the "bar plot" graphic type.

Yes I am having this problem too!

**Pull request merged**
