### PR TITLE
adds plot refresh on layer dataChanged signal

### LINKED ISSUE #116: Update plot on data changed
I'm using DataPlotly with a plugin that will allows user to click on a point on the map to see time series at this point.

The source of the plot is a layer with 3 attributes: time, point_id, value

The click on the map changes the layer filter on point_id (got the idea from TimeManager plugin).

Refreshing the plot when the source layer data is changed would be a nice addition IMO.

I'll PR if I succeed.

### PR DESCRIPTION
**Pull request by vmora**
the title says it all

fixes #116

### CODE REVIEW

**Comment by ghtmtt** [comment]
Hi @vmora I fetched the PR and (of course) nothing is changed from DataPlotly usage. Do you mind to provide a small gif or general documentation of what is this specific usage? I'd like to highlight it somewhere ;)

**Comment by nyalldawson** [comment]
@ghtmtt the dataChanged is rarely fired (usually only as a result of something changing on the provider side). One way to get it to emit is by setting a filter on a layer -- that's the easiest way to test this.

**Comment by vmora** [comment]
@nyalldawson I got caught for the second time with this signal supposing that it was also fired after layer edition, which it is not. 

I guess I should also connect to `editCommandEnded` or `repaintRequested` to keep graph in siync with data.

**Comment by ghtmtt** [comment]
@nyalldawson do you think some changes have to be done before merging the PR?

**Comment by nyalldawson** [comment]
@vmora 

> I guess I should also connect to editCommandEnded or repaintRequested or layerModified to keep graph in siync with data.

I think layerModified is the right signal -- definitely don't do repaintRequested as that is fired for layer symbology changes as well as feature changes.

**Comment by vmora** [comment]
@nyalldawson thanks, will do next week.

**Comment by nyalldawson** [comment]
Superseded by #154

**Pull request closed without merging**
