### PR TITLE
Refactoring pt 1

### PR DESCRIPTION
**Pull request by nyalldawson**
And attempt to get Travis CI live...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@ghtmtt can you please enable Travis for this repo?

**Comment by ghtmtt** [comment]
> @ghtmtt can you please enable Travis for this repo?

done

**Comment by nyalldawson** [comment]
@ghtmtt This can be merged now -- there's likely a bit of breakage due to the code shuffle, but it's only the very first stage, and I'd love to have the CI in place as I continue the refactoring

**Comment by ghtmtt** [comment]
@nyalldawson yeah! We have travis now!

**Pull request merged**
