### PR TITLE
move layout properties to layout options group in widget

### PR DESCRIPTION
**Pull request by SGroe**
I would like to move all layout properties (e.g. plot title) to the new layout option group (introduced by #259). Only the ui file is changed here.

These layout properties only apply to the first plot, if multiple plots in a layout are defined. One idea I have in my mind is to (optionally) synchronize these layout properties across all plots of a layout item (to be done in a future pr).

@ghtmtt: What do you think about that? I you like that, I would add some minor improvements.

dataploty_layout_properties

### CODE REVIEW

**Comment by ghtmtt** [comment]
@SGroe I'm +1 on that. The layout configuration *box* can be extended with a lot of new widgets (axis color, fonts, sizes, etc) but this will be also something to think in a future (many actually ;) ) PR. But we should discuss this somewhere else.

This is ploty *chart studio*: https://chart-studio.plotly.com/create/#/  where basically all plotly customization are available (p.s. I never used chart studio ;) ).

**Comment by SGroe** [comment]
@ghtmtt, what do you think about moving the remaining non-layout properties to the first settings page (within "Properties" group). These include:

- Legend title
- Hover tooltip
- Hover label as text
- Label text position
- Bar orientation
- Normalization
- Show statistics
- Outliers
- Violin side
- Include box plots
- Show mean line
- Invert histogram direction
- Cumulative histogram
- Manual bin size

**Comment by ghtmtt** [comment]
are you suggesting to move basically all the widgets of the *Advanced Configuration* within the *Layout Options* block?

**Comment by SGroe** [comment]
I suggest to move the mentioned properties (legend title, hover tooltip, ...) to the "Properties" group on the first page. Currently, this group contains properties like "Marker Color" or "Opacity".

**Comment by SGroe** [comment]
Here are two screenshots. Note that the properties "Label text position" and "Bar orientation" moved from the second to the first page.

widget1

widget2

**Comment by ghtmtt** [comment]
I'd move the `Legend Title` to the `Layout Options` for the rest +1

**Comment by SGroe** [comment]
I can move it from 'Plot properties' to 'Properties'. I don't want to move it to the 'Layout options' because this group should only contain (layout) properties. Layout properties are set once and apply for all sub plots. The 'Legend Title' will be different for each sub plot.

**Comment by ghtmtt** [comment]
got it, + 1 for me! Thanks

**Comment by SGroe** [comment]
Here is an updated screenshot. I have moved 'Legend Title' to the 'Properties' group.

widget3

**Pull request merged**
