### PR TITLE
Unify dock appearance with layer styling dock

### PR DESCRIPTION
**Pull request by nyalldawson**
Minor UI tweaks to improve appearance and consistency of dock

### CODE REVIEW

**Comment by ghtmtt** [comment]
thanks for the PR. Can I merge it or some other commits are coming ;) ?

**Comment by nyalldawson** [comment]
All done for now... Was just getting things ready for some screenshots

**Comment by nyalldawson** [comment]
I think that might be useful. It's minor tweaks, but it does make it all look more integrated rather than added on. In the post I'm currently working on I encourage people to download and test the current version of the plugin, so it'd be good go them the extra polish too.

**Comment by ghtmtt** [comment]
ok will do that tomorrow morning asap. thanks!

**Comment by ghtmtt** [comment]
done, thanks!

**Pull request merged**
