### PR TITLE
antother better approach to save and reload config

### PR DESCRIPTION
**Pull request by ghtmtt**
Should fix #184. @SGroe it this the approach you was suggesting to use?

### CODE REVIEW

**Comment by SGroe** [comment]
I cannot test this right now, but yes, this is the approach.

**Comment by ghtmtt** [comment]
@danpejobo  are you able to test the patch of this PR?

**Comment by danpejobo** [comment]
@ghtmtt yeah i can test it

**Comment by ghtmtt** [comment]
> @ghtmtt yeah i can test it

thanks! Let me know if it is working so I can release the updated version

**Comment by danpejobo** [comment]
> > @ghtmtt yeah i can test it
> 
> thanks! Let me know if it is working so I can release the updated version

Seems to be working now! on all my projects. Tested with my regular userprofile and the new one as well. No errors for me.

**Pull request merged**
