### PR TITLE
Add expression widgets for histograms, pie charts and box plots.

### LINKED ISSUE #167: changing color for pie chart
It seems that it's actually impossible to change color of generated pie charts. Unless I missed the option, is it possible to add the functionality ?

### LINKED ISSUE #188: Add `color` attribute for histograms
For the use case of using histograms as legends (https://gis.stackexchange.com/q/207208/1931) it is necessary to colour the individual bars of the histogram using different colours.

Plotly currently does not have an option for automatically colouring the bars of a histogram using a colorscale (https://github.com/plotly/plotly.js/issues/1984), but it is possible to provide an array of color names to the `marker.color` attribute (https://plot.ly/javascript/reference/#histogram-marker-color). If this was exposed using the DataPlotly GUI using a field that allows an expression to be used, it would be possible to create the histogram legend described above.

image

### PR DESCRIPTION
**Pull request by jdugge**
This PR adds expression widgets for the colors of histograms, pie charts and box plots.

This allows specifying the colors of:

 - individual histogram bars (fixes #188)
 
image

    array_foreach(generate_series( 0, 1.01, 1/9 ),  ramp_color( 'RdYlGnBu', @element))

 - individual pie segments (fixes #167)

image

    ramp_color( 'RdYlGnBu', ("IMDD15"-1)/9)

 - box plots (unfortunately, to get different colors for the individual boxes, it is necessary to use separate plots)

image

### CODE REVIEW

**Comment by ghtmtt** [comment]
great enhancement! User question: to get the same histogram color of a graduated layer classification, the user has to enter one of the expression you put in this PR text, right? I'm afraid some users will be scared by these expressions, what about adding a tooltip (or something similar)? 

Finally we should also add this in the documentation.

**Comment by ghtmtt** [comment]
> individual pie segments (fixes #167)

could you please share a small dataset sample? I'm trying to look deeper into this

**Comment by jdugge** [comment]
> to get the same histogram color of a graduated layer classification, the user has to enter one of the expression you put in this PR text, right?

Yes, that's right. One could write a function for use in the expression that makes this easier, but to really make this user friendly it would probably be better to have a check box "link colors to layer symbology"

> I'm afraid some users will be scared by these expressions, what about adding a tooltip (or something similar)?

I've adjusted the help text in the expression editor now to mention the fact that the user can supply an array of colors rather than a single color name
 
> Finally we should also add this in the documentation.

I'll add something to the documentation

> could you please share a small dataset sample?

You can use the Natural Earth [`ne_10m_populated_places_simple`](https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-populated-places/) dataset with the expression `ramp_color( 'RdYlGnBu', ("scalerank" - 1)/9)` to try this out.

**Comment by nyalldawson** [comment]
> I'm afraid some users will be scared by these expressions, what about adding a tooltip (or something similar)?

Personally I don't see this as an issue -- they are standard QGIS expressions, and they can be auto-created via a UI by using the inbuilt "assistant" option.

@jdugge can you rebase this to fix the conflicts and add a unit test?

**Comment by jdugge** [comment]
I'll be glad to add a unit test, but I'm struggling a bit with getting the tests to run successfully again (in particular `test_read_write_project_with_layout`). Should the tests all be passing at the moment?

**Comment by ghtmtt** [comment]
> I'll be glad to add a unit test, but I'm struggling a bit with getting the tests to run successfully again (in particular test_read_write_project_with_layout). Should the tests all be passing at the moment?

Travis is giving us some problems due to an internal service migration, but I think you are testing also locally.

It is very important to test if QGIS projects saved with some DataPlotly configuration are not broken with the new feature. That's something I've on the ToDo list (to add project *regression* tests).

**Comment by jdugge** [comment]
The tests are now basically passing (the tests time out with the latest QGIS version, but I don't think that has anything to do with the new features).
Could you give me some more details on what kind of tests I should add so this PR can be merged?

**Comment by ghtmtt** [comment]
@jdugge no problem for me! I'm still having some troubles to get the correct colors in the pie chart, with the expression `ramp_color( 'Blues', ("Cases"-1)/9)`. 

immagine

**Comment by jdugge** [comment]
> I'm still having some troubles to get the correct colors in the pie chart, with the expression `ramp_color( 'Blues', ("Cases"-1)/9)`.

That expression would work if "Cases" was a field containing only the values of 0 to 9 (like the "scalerank" field in the Natural Earth `populated_places` dataset.

In your case, you would an expression like the following:

```
CASE
	WHEN "Deaths" < 41 THEN ramp_color('Blues', 0/4)
	WHEN "Deaths" < 237 THEN ramp_color('Blues', 1/4)
	WHEN "Deaths" < 1112 THEN ramp_color('Blues', 2/4)
	WHEN "Deaths" < 7114 THEN ramp_color('Blues', 3/4)
	ELSE ramp_color('Blues', 4/4)
END
```

It would be nice if the `@symbol_color` variable would be available in the DataPlotly context, then we could simply use that in the color expression.

**Comment by ghtmtt** [comment]
got it. I really think we should add this to the documentation. I can do it but I'll maybe ping you for a review.

Really nice new cool feature! Thanks @jdugge

**Pull request merged**
